version: '3.3'

services:

  # ElasticSearch Service
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.2
    container_name: elasticsearch
    # volumes:
    #   - ~/volumes/jhipster/jhipster/elasticsearch/:/usr/share/elasticsearch/data/
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 9200:9200
    environment:
      - network.host=0.0.0.0
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - node.name=cluster1-node1
      - xpack.license.self_generated.type=basic
      - xpack.security.enabled=false
      - xpack.security.authc.api_key.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    networks:
      - elk

  # Kibana Service
  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.2
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      SERVER_HOSTS: 0.0.0.0
    ports:
      - 5601:5601
    networks:
      - elk
    depends_on:
      - elasticsearch

# Network for app
networks:
  elk:
    driver: bridge
